services:
  backend:
    build:
      context: ./backend
    expose:
      - "8000:8000"
    env_file:
      - .env                # ✅ load variables from .env
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8000
      - GROK_API_KEY      # ✅ allow override or passthrough

  frontend:
    build:
      context: ./frontend
    expose:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000
      - PORT=8501
