services:
  backend:
    build:
      context: ./backend
    ports:        
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8000
      - GROQ_API_KEY

  frontend:
    build:
      context: ./frontend
    ports:        
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000
      - PORT=8501
