services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000
