services:
  backend:
    build:
      context: ./backend
    expose:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8000

  frontend:
    build:
      context: ./frontend
    expose:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000
      - PORT=8501