services:
  - type: web
    name: docs-backend
    env: docker
    repo: https://github.com/draxBlob27/docs_chatbot
    dockerfilePath: backend/Dockerfile
    buildFilter:
      paths:
        - backend/**
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: PORT
        value: 8000

  - type: web
    name: docs-frontend
    env: docker
    repo: https://github.com/draxBlob27/docs_chatbot
    dockerfilePath: frontend/Dockerfile
    buildFilter:
      paths:
        - frontend/**
    envVars:
      - key: API_URL
        value: https://docs-backend.onrender.com
      - key: PORT
        value: 8501
