services:
  - type: services
    name: docs-backend
    env: docker
    repo: https://github.com/draxBlob27/docs_chatbot
    dockerfilePath: backend/Dockerfile
    plan: free
    buildFilter:
      paths:
        - backend/**
    envVars:
      - key: GROQ_API_KEY
        sync: false

  - type: services
    name: docs-frontend
    env: docker
    repo: https://github.com/draxBlob27/docs_chatbot
    dockerfilePath: frontend/Dockerfile
    plan: free
    buildFilter:
      paths:
        - frontend/**
    envVars:
      - key: API_URL
        value: http://docs-backend:8000
