services:
  - type: web
    name: backend
    env: docker
    repo: https://github.com/draxBlob27/docs_chatbot
    dockerfilePath: backend/Dockerfile
    plan: free
    region: oregon
    buildFilter:
      paths: 
        - backend/**
    envVars:
      - key: GROQ_API_KEY
        sync: false

  - type: web
    name: frontend
    env: docker
    repo: https://github.com/draxBlob27/docs_chatbot
    dockerfilePath: frontend/Dockerfile
    plan: free
    region: oregon
    buildFilter:
      paths:
        - frontend/**
    envVars:
      - key: API_URL
        value: http://backend:8000
