services:
  - type: web
    name: backend
    env: docker
    repo: https://github.com/draxBlob27/docs_chatbot
    dockerfilePath: backend/Dockerfile
    context: .
    plan: free
    region: oregon
    buildFilter:
      paths: 
        - backend/**
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: PORT
        value: 8000

  - type: web
    name: frontend
    env: docker
    repo: https://github.com/draxBlob27/docs_chatbot
    dockerfilePath: frontend/Dockerfile
    plan: free
    region: oregon
    buildFilter:
      paths:
        - frontend/**
    envVars:
      - key: PORT
        value: 8501
      - key: BASE_URL
        fromService:
          type: web
          name: backend
          property: host